spring:
  datasource:
    url: jdbc:h2:mem:registrydb
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: payment-api
server:
  port: 8082
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

